language: node_js

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
  
after_script:
  - codeclimate-test-reporter < lcov.info

script: grunt default --verbose --force

addons:
    code_climate:
        repo_token: ebd7144a5a22962119457649c88081b426611cd447e94c91ad427fec2e3bed46
